### ISSUE TITLE
vsnprintf() behavior mismatch

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#118]
`gdb` uses `vsnprintf()` to determine the size needed for a buffer like so

```
va_copy (vp, args);
size = vsnprintf (NULL, 0, fmt, vp);
va_end (vp);
```

However, while testing in managarm, this behaviour isn't matched, and size is 0, which crashes gdb. We should match the behaviour of glibc and the likes in this case

**Comment by ArsenArsen** [comment]
Note to future readers: The correct behavior, per POSIX and C99, is to not treat size=0 any differently to a normal call, and simply return the number of bytes that *would have* been used. Attention should also be taken, as `str` might also be `NULL` and considered valid, to not access `str`.
