### ISSUE TITLE
when compiling mlibc configured to ansi-c only, i get errors about missing posix headers

### ISSUE THREAD

**Issue by BrainStackOverFlow** [managarm/mlibc#138]
error message: https://pastebin.com/FiASwneX
mlibc meson.build: https://pastebin.com/G70T1S84

**Comment by Geertiebear** [comment]
This issue should have been fixed in #147. @BrainStackOverFlow can you verify it works now?

**Comment by Geertiebear** [comment]
I'll close this issue, we test against ansi-only builds now.
