### ISSUE TITLE
Missing getline/getdelim

### ISSUE THREAD

**Issue by alula** [managarm/mlibc#18]
Prevents many programs from compiling, standarized by POSIX.

http://man7.org/linux/man-pages/man3/getline.3.html

**Comment by avdgrinten** [comment]
Thank you for the report. This is indeed something we should fix.

Out of curiosity: on which OS do you use mlibc?

**Comment by gabixdev** [comment]
I've tried to build some stuff on qword and had to add a stub for these functions to make it build
