### ISSUE TITLE
posix: Implement recursive mutexes

### ISSUE THREAD

**Issue by avdgrinten** [managarm/mlibc#21]
Our `pthread_mutex` struct already has a member to store the level of nested locks but it is not used yet. Add a `sys_futex_tid` function to get a per-thread ID. When locking a mutex, store the `sys_futex_tid` in the mutex (instead of 0/1, as we currently do).

**Comment by thomtl** [comment]
Fixed in bf682e41dbd9bb95284139c520dbf29f57e81b23 i presume?

**Comment by avdgrinten** [comment]
Corrrct.
