### ISSUE TITLE
ld.so: Find DSO even if dladdr() symbol is not found

### ISSUE THREAD

**Issue by avdgrinten** [managarm/mlibc#211]
The Linux man page specifies the following behavior of dladdr() if the given address does not match a symbol:

> On success, these functions return a nonzero value. If the address specified in addr could be matched to a shared object, but not to a symbol in the shared object, then the info->dli_sname and info->dli_saddr fields are set to NULL.

This behavior is not currently implemented in mlibc.

**Comment by Geertiebear** [comment]
Is this issue the cause of #207 maybe?
