### ISSUE TITLE
posix: Implement pthread_attr_*

### ISSUE THREAD

**Issue by 64** [managarm/mlibc#253]
These are used by the Rust standard library when spawning a thread, specifically:
* `pthread_attr_init`
* `pthread_attr_setstacksize`
* `pthread_attr_destroy`

**Comment by avdgrinten** [comment]
Since this breaks ABI, we probably want to implement all the pthread functionality in one iteration, possibly for mlibc 3.0.

**Comment by Geertiebear** [comment]
This has been fixed in #311.
