### ISSUE TITLE
ansi: Implement (a subset of) strptime

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#276]
Several programs require `strptime` to properly function. Notable users of this are `wget` and `xbps-install` on Managarm. Implementing this would allow these programs to behave better.

**Comment by ikbenlike** [comment]
#332 has now been merged. Do the implemented directives satisfy `xbps-install` requirements or does it also depend on locale-specific directives?

**Comment by Geertiebear** [comment]
grepping for ``strptime()`` shows this: ```lib/fetch/http.c:       r = strptime(p, "%a, %d %b %Y %H:%M:%S GMT", &tm);
lib/fetch/http.c:               r = strptime(p, "%a, %d %b %Y %H:%M:%S UTC", &tm);``` so I think we're okay.

**Comment by ikbenlike** [comment]
The `%a` and `%b` directives are not yet implemented. They match with the name of the day and the name of the month, respectively (both the full name and abbreviations).

**Comment by Dennisbonke** [comment]
This issue still stands, and blocks `wget` on Linux from functioning without hacks. `wget` triggered the ensures for `%a`, `%A`, `%b`, `%B` and `%h`. Not all of those might be needed. If someone could take this on that would be great.
