### ISSUE TITLE
ld.so: Integrate into static build

### ISSUE THREAD

**Issue by avdgrinten** [managarm/mlibc#29]
Currently, we do not use the dynamic linker in static builds. That is problematic for two reasons:
- `dlopen()` will not work
- ld.so is responsible for allocating thread-local storage (TLS)

Fix this by linking the dynamic linker into the static library. Use the (undocumented) `__ehdr_start` symbol to find the ELF EHDR of the executable. Read the PHDR offset from the EHDR and use that to find the executable's PHDRs. Then proceed to do dynamic linking as usual (naturally, there will be no relocations, so this will mostly be a no-op).

As an additional benefit, this change will unify the initialization paths (for `.init_array` etc.) in the static and dynamic cases.

**Comment by Geertiebear** [comment]
Fixed by PR #31
