### ISSUE TITLE
Unknown format specifiers in WebKitGTK

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#346]
`WebKitGTK` uses `register_printf_specifier` and `register_printf_type` to register custom printf specifiers, including stuff like `%{public}s`. We don't implement those, thus crashing mlibc when this type is used. While I can work around it by patching it in webkit, tho implementing this would be the preferred solution.

**Comment by avdgrinten** [comment]
Does WebKit do that unconditionally? Does musl even support these functions?

**Comment by Geertiebear** [comment]
Musl seems to have no mention of ``register_printf_specifier``.

**Comment by 64** [comment]
`{public}s` seems to actually be an Apple `os_log` feature, not something that even glibc supports, so this seems to be a WebkitGTK bug (https://bugs.webkit.org/show_bug.cgi?id=207478). It looks like they've already fixed this: https://github.com/WebKit/WebKit/blob/23272376caff6f758cfb154dc6721b545e313d71/Source/WTF/wtf/Assertions.h#L552-L573.

Based on that, I think we can close this issue and reopen it if we find something that truly needs `register_printf_specifier`.
