### ISSUE TITLE
strptime directives unimplemented

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#352]
An user testing managarm found out that `xbps-install --sync base-devel` triggered a call to `strptime` with either `%a`, `%A` or both of them. As these aren't implemented, this fails. Implementing these would allow `xbps-install` to continue further.

Continuation of #276

**Comment by RaidTheWeb** [comment]
can confirm :)))

**Comment by Geertiebear** [comment]
This is just a duplicate of #276 no?

**Comment by Dennisbonke** [comment]
As geert mentioned, duplicate of #276
