### ISSUE TITLE
ansi: ungetc hangs if lock is already acquired

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#408]
If a program locks a file or stream with `flockfile()` and then calls `ungetc()` on said file or stream, the program will hang on acquiring the lock in ungetc. This behaviour was observed in gtk3 running on Managarm. A hotfix of `funlockfile()` -> `ungetc()` -> `flockfile()` fixed that issue, pointing again at an issue with our locking implementation used by `ungetc()`.

**Comment by ArsenArsen** [comment]
Is this not a GTK/GLib bug? `ungetc` doesn't have a nonlocking counterpart and does not specify that it should behave any differently on locks. (unrelated, but, what kind of insane mess needs ungetc anyway?)

**Comment by Dennisbonke** [comment]
> Is this not a GTK/GLib bug? `ungetc` doesn't have a nonlocking counterpart and does not specify that it should behave any differently on locks. (unrelated, but, what kind of insane mess needs ungetc anyway?)

It could be a `GTK` bug, but then why does it work on Linux? I see nothing to indicate it takes a different code path. As for the insane mess, see [this](https://gitlab.gnome.org/GNOME/gtk/-/blob/3.24.23/gtk/gtkutils.c#L107) function, it has two calls to `ungetc()`.

**Comment by avdgrinten** [comment]
Well, POSIX doesn't specify that you can lock a file recursively AFAICT. So GTK's code makes non-POSIX assumption and only works on Linux by chance. Still, this can be fixed easily in our code.

**Comment by avdgrinten** [comment]
Ah, in this case, GTK is compliant.

Anyway, the fix remains the same.
