### ISSUE TITLE
Adding (minimal) atomic_ops.h or sys/atomic.h support

### ISSUE THREAD

**Issue by YusufKhan-gamedev** [managarm/mlibc#417]
I need the atomic_t type and the atomic_set function to add dri hardware acceleration(i915/i965, nv, and r100/r200 gpus).

This issue is for the case that I do not get the time to add this into mlibc(quite probable!).

**Comment by YusufKhan-improves-shit** [comment]
NOTE: atomic_set comes from https://github.com/tobiasjakobi/libdrm/blob/exynos/xf86atomic.h I am not referring to a libc call!

**Comment by YusufKhan-improves-shit** [comment]
Bingo! Found a WAY better workaround so I wont be commiting anything to mlibc. Check mesa/src/mesa/drivers/common/xf86atomic.h for the workaround when I publish the mesa fork.
