### ISSUE TITLE
Static and shared libraries cannot be built simultaneously

### ISSUE THREAD

**Issue by 64** [managarm/mlibc#514]
To fix this, we should probably replace our ad-hoc `static` option with meson's built in `default_library` option (which can be set to a value of 'both').

**Comment by avdgrinten** [comment]
Can we detect whether a file is built as part of the static lib or as part of the shared lib? Our shared and static libs have slightly different behavior.

**Comment by 64** [comment]
I don't think so, but the behaviour only seems to differ in `ld.so`. I think it's sufficient to do something a bit hacky like
```
if default_library == 'static' or default_library == 'both'
	ld_static = static_library('ld', '-DMLIBC_STATIC_BUILD')
endif
if default_library == 'shared' or default_library == 'both'
	ld_shared = shared_library('ld')
endif
```
