### ISSUE TITLE
posix: Incorrect realpath behavior

### ISSUE THREAD

**Issue by czapek1337** [managarm/mlibc#528]
The function is supposed to return "/" when passed "/", but instead returns an empty string. I wrote a simple program to test that behavior:
```cpp
#include <stdio.h>
#include <stdlib.h>

int main() {
	printf("'%s'\n", realpath("/", NULL));
	printf("'%s'\n", realpath("/tmp", NULL));
	return 0;
}
```
Results when building against GLIBC were as expected, that is: `/` and `/tmp`, however mlibc resulted in an empty string in the first case. I'm fairly certain the problem lies in here, but I'm not sure how to fix it: https://github.com/managarm/mlibc/blob/110693bf2520da24da68bb6f2264d480317d1955/options/posix/generic/posix_stdlib.cpp#L356-L360

**Comment by avdgrinten** [comment]
This has nothing to do with `basename()`, does it? We're not using `basename()` in our `realpath()` implementation.

**Comment by ArsenArsen** [comment]
Oh, I misread that, apologies
