### ISSUE TITLE
Unknown printf() specifiers

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#57]
While testing the coreutils programs the following utilities required an unimplemented `printf()` specifier ('76')

- `seq`
- `dd`

The following program required the unimplemented `printf()` specifier ('39'), which converts to an `'`

- `xz`

Furthermore, it seems we are lacking an implementation of `%f`

**Comment by Dennisbonke** [comment]
Converting 76 to ascii yields `L`, which seems to be an specifier for a `long double` conversion

**Comment by Geertiebear** [comment]
Support for `'` has been added as of https://github.com/managarm/frigg/commit/070aadc38552f226c64a015f050618a48918584f
