### ISSUE TITLE
rtdl: Ensure triggered in R_X86_64_TPOFF64

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#578]
While testing `libasan` on mlibc LFS, we ran into [this](https://github.com/managarm/mlibc/blob/a53280ab5fa0a851b62abcbf77bf0c41707199a1/options/rtdl/generic/linker.cpp#L1295) ensure. Fixing it would allow us to use `libasan`.

**Comment by 64** [comment]
I think we can just add the addend here.
