### ISSUE TITLE
printf formatting issues

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#58]
While testing the coreutils programs on managarm the `stat` program crashed with the following error:

`../../../src/mlibc/subprojects/frigg/include/frg/formatting.hpp:379: Assertion '!opts.left_justify' failed!`

This can be reproduced by `stat`ing any regular file.

Running the following command gives the same error, on a different location, this time at line 459
`readelf -I <executable>`

**Comment by Dennisbonke** [comment]
Running `python3 --help` on Managarm produces the following error:

```
../../../src/mlibc/subprojects/frigg/include/frg/formatting.hpp:381: Assertion 'szmod == printf_siz

_mod::default_size' failed!
```

**Comment by Geertiebear** [comment]
I think this issue can be closed right?

**Comment by 64** [comment]
I agree - can't reproduce anymore

**Comment by Dennisbonke** [comment]
I'll test it in a bit and close it if I can't reproduce as well

**Comment by Dennisbonke** [comment]
Can confirm, issue is fixed. Closing
