### ISSUE TITLE
rtdl: dynamic linker may load libraries more than once

### ISSUE THREAD

**Issue by 64** [managarm/mlibc#585]
This can easily occur if e.g a library is loaded first by `path/to/libfoo.so` and then `libfoo.so`, where the latter name is resolved via an RPATH.

**Comment by ArsenArsen** [comment]
Note to implementor: AFAIU, these should be deduplicated based on SONAME, falling back on (st_dev,st_ino) or such

**Comment by 64** [comment]
As far as I can tell from some testing, glibc does a bit more than just matching on SONAME.

What I tried was creating two libraries `libfoo.so` and `libbar.so`, and passing `-Wl,-soname=libfoo.so` to them both. Then we would expect the following program to succeed, but it fails on the bottom assert, despite both objects having the same SONAME (verified via `readelf -d`):
```c
#include <dlfcn.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>

#define LIBFOO "libfoo.so"
#define LIBBAR "libbar.so"

int main() {
	void *foo = dlopen(LIBFOO, RTLD_NOW);
	void *bar = dlopen(LIBBAR, RTLD_NOW);
	assert(foo);
	assert(bar);
	assert(foo == bar);
}
```

I'm not quite sure where this leaves us then. Maybe glibc only uses SONAME if it's a substring of the file name (i.e libc.so vs libc.so.6), or maybe it doesn't use SONAME at all for this purpose?

**Comment by ArsenArsen** [comment]
Well, guessing won't get us anywhere.

https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-open.c;h=a23e65926bcfe797f06f8b4175f65040f4547a05;hb=HEAD#l77

https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-load.c;h=1ad0868dad809d56c7ecced65ce482af4982abc9;hb=HEAD#l1947

The dlopen `name` argument is compared against SONAMEs, hence, your test will succeed if libbar is loaded first.

```c
[i] ~$ echo '' | gcc -shared -o libfoo.so -Wl,-soname=libfoo.so -x c -
[i] ~$ cp libfoo.so libbar.so
[c] ~$ gcc -Wl,-rpath='$ORIGIN' test1.c
[c] ~$ ./a.out 
[i] ~$ cat test1.c
#include <dlfcn.h>
#include <stdio.h>
#include <assert.h>
#include <string.h>

#define LIBFOO "libfoo.so"
#define LIBBAR "libbar.so"

int main() {
	void *bar = dlopen(LIBBAR, RTLD_NOW);
	void *foo = dlopen(LIBFOO, RTLD_NOW);
	assert(foo);
	assert(bar);
	assert(foo == bar);
}
```
