### ISSUE TITLE
x86 port

### ISSUE THREAD

**Issue by FedorLap2006** [managarm/mlibc#699]
Port of mlibc internals and sysdeps to x86 (i386) architecture.

## Internals
- [x] RTDL entrypoint
- [x] Architecture specific headers
- [x] ABI
- [x] Architecture-abstract types
- [x] RTDL relocations
- [x] Tests

## Sysdeps
- [x] Linux (i386)
- [x] DepthOS

**Comment by moodyhunter** [comment]
Hello, what's the current process on this?
I'm currently seeking for a libc for my x86 (i686) OS :)

**Comment by FedorLap2006** [comment]
> Hello, what's the current process on this? I'm currently seeking for a libc for my x86 (i686) OS :)

Sorry for a late reply. If that's still relevant, the port can currently run staticly linked applications (e.g. bash).
However, it's quite out of date with the main branch.

I'm planning to return to its development soon, so if you have any problems, an issue on the fork repo is welcome.

**Comment by moodyhunter** [comment]
Hi, thanks for your reply.
I do have plans to add dynamic-linked lib support (both for my OS and mlibc), but I don't have much time recently so my requirement isn't urgent.

Appreciate your work anyway :)

**Comment by FedorLap2006** [comment]
@moodyhunter it took us a while, but it's done now! Currently it's not merged yet, but you can already base off our branch since it's currently sitting on top of `master`.
