### ISSUE TITLE
getaddrinfo() unimplemented

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#89]
With the recent addition of tcp to managarm, it has become clear that we are lacking in name resolution. One major example is `getaddrinfo()`, required by at least  `git` from my initial testing. We should strive to implement this as soon as possible

**Comment by Dennisbonke** [comment]
On closer inspection we do have an partial implementation of `getaddrinfo()`, however, should the service argument be anything other then NULL, that is unimplemented. It seems `git` uses the service argument, thus triggering the `__ensure`

**Comment by Geertiebear** [comment]
Closed in favour of tracking issue #99
