### ISSUE TITLE
regcomp() unimplemented

### ISSUE THREAD

**Issue by Dennisbonke** [managarm/mlibc#98]
The following programs, tested on managarm, require `regcomp()` to properly function

- `file`, `file` works for executables, but for other files, `regcomp()` is called, thus severely limiting it's use.
- `flex`, all programs from `flex` want `regcomp()`. Without it, even `flex --help` fails

**Comment by 64** [comment]
Instead of writing our own regex implementation, we could port an existing one such as https://github.com/kokke/tiny-regex-c or musl's

**Comment by 64** [comment]
This needs the 'affects ABI' label.
