### ISSUE TITLE
dirent has wrong ABI on linux

### ISSUE THREAD

**Issue by no92** [managarm/mlibc#980]
`dirent`'s `d_name` member is 256 bytes large on Linux, while mlibc defines it to be 1024 bytes large.

**Comment by qookei** [comment]
A simple fix would just be using `NAME_MAX + 1` in place of 1024 in the struct definition, but I don't think the length of `d_name` strictly matters from a Linux ABI point of view. `sys_read_entries` writes a tightly-packed array of `struct dirent`-looking entries, with the position of the next entry being determined by `d_reclen`, not by the static size of the entry.


https://github.com/managarm/mlibc/blob/5454a4860bbecfd99bf85ad0e8282d51844368a5/options/posix/generic/dirent-stubs.cpp#L78-L81
